Feat (angular) dont show devtools in prod
tryabby/abby pull request #23
Opened 2023-06-07 14:25 UTC by trishouser

2023-06-08 11:34 UTC, Tim-53 requested changes
Devtools should be shown if env is dev or prop is set

2023-06-08 12:16 UTC, trishouser commented on packages/angular/src/lib/devtools.component.ts
> +      this.props?.["dangerouslyForceShow"] &&
you're right. I fixed it

2023-06-09 11:12 UTC, Tim-53 requested changes

2023-06-09 11:12 UTC, Tim-53 commented on packages/angular/src/lib/devtools.component.ts
> +      this.props?.["dangerouslyForceShow"] ??
```suggestion
      this.props?.["dangerouslyForceShow"] ||
```

2023-06-09 11:14 UTC, Tim-53 approved these changes

2023-06-09 12:37 UTC, merged