feat(tracking): use Plausible for tracking
tryabby/abby pull request #54
Opened 2023-08-09 14:49 UTC by CakeWithDivinity

Adds simple tracking of actions done on the landing page and dashboard. Also tracks the usage of our APIs.
This uses https://plausible.io/

2023-08-09 14:54 UTC, CakeWithDivinity commented
Dunno why the Vercel docs pipeline fails again. Probably the same issue as last time ¯\_(ツ)_/¯

2023-08-14 08:54 UTC, cstrnt requested changes

2023-08-14 08:54 UTC, cstrnt commented on TRACKING.md
> +| Sign Up Clicked            | a user clicks the Singup Button on the landing page                                                                                      | None
```suggestion
| Sign Up Clicked            | a user clicks the Signup Button on the landing page                                                                                      | None                                                                                |
```

2023-08-14 08:54 UTC, cstrnt commented on apps/web/src/pages/_document.tsx
> +        )}
I believe that the  `PlausibleProvider` in the `_app.tsx` file does this already

2023-08-14 08:54 UTC, cstrnt commented on apps/web/.env.example
> +PLAUSIBLE_DOMAIN=tryabby.com
It would be nice if you could add this to the `schema.mjs` file and then access the env vars in a typesafe way rather than `process.env.SOMETHING`

2023-08-14 14:11 UTC, cstrnt commented
Types for `next-plausible` are currently off :( Let's wait the PR here https://github.com/4lejandrito/next-plausible/pull/102 and a new version :D

2023-08-14 14:22 UTC, merged