feat(cli): implement add flag and config commands
tryabby/abby pull request #81
Opened 2023-10-06 12:47 UTC by CakeWithDivinity

See #80 

The commands look like this:
![image](https://github.com/tryabby/abby/assets/29003122/bf1c8a3c-7201-40f9-9c92-c4a2355e6132)

2023-10-10 09:07 UTC, cstrnt requested changes
I think this might be related to the `mergeConfigs` function but it resolves the .env vars and then alters the config. Maybe just do a atomic update on the config?

<img width="948" alt="Screenshot 2023-10-10 at 11 04 44" src="https://github.com/tryabby/abby/assets/20679094/38d4769b-981d-4a03-963c-4409a5f90622">

2023-10-10 09:07 UTC, cstrnt commented on packages/cli/src/add-flag.ts
> +  await push({ apiKey: options.apiKey, configPath: options.configPath, apiUrl: options.host });
I think there should be some sort of rollback here if the push fails

2023-10-16 07:16 UTC, cstrnt commented
![Screenshot 2023-10-16 at 09 15 41](https://github.com/tryabby/abby/assets/20679094/a9dc0a9a-358c-4e58-8e9f-76df573ed888)
Something is still odd with the formatting after the file gets updated @CakeWithDivinity

2023-10-20 08:01 UTC, CakeWithDivinity commented
@cstrnt Should be fixed now. We now only replace newlines in the `defineConfig(...)` part. The issue was that when the newlines were missing in the first line, it was still a correctly formatted file for prettier. This way, this should only happen in the part of the file that we actually want to edit.

2023-11-06 09:22 UTC, cstrnt approved these changes

2024-01-07 15:30 UTC, cstrnt commented
Current dependencies on/for this PR:
* `main`
  * **PR #81** <a href="https://app.graphite.dev/github/pr/tryabby/abby/81?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/tryabby/abby/81?utm_source=stack-comment).

2024-01-07 15:46 UTC, merged